### ISSUE TITLE
Ran PyFunceble on hosts

### ISSUE THREAD

**Issue by sr093906** [jdlingyu/ad-wars#13]
PyFunceble -f https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts -c --dns 1.2.4.8 8.8.8.8

The project decides whether a domain is active by three dimensions, HTTP status code, WHOIS record and DNS Lookup.

More info:
https://pyfunceble.readthedocs.io/en/latest/usage/index.html#from-a-terminal

These domains are marked as INACTIVE 

 m.irs01.com
 z.irs01.com
 sdk2.youguoquan.com
 rlog-video.conn.aiseet.atianqi.com
 afp.qiyi.com
 focusbaiduafp.allyes.com
 sohu.irs01.com
 api.game.letvstore.com
 dev.dc.letv.com
 msg.m.letv.com
 api.adv.ott.cibntv.net
 tpptv.ipdx.cn.miaozhen.com
 mdrecv.app.cntvwb.cn
 sdapprecv.app.cntvwb.cn
 vdapprecv.app.cntvwb.cn
 a.cctv.com
 dspserver.ad.cmvideo.cn
 test.ad.cmvideo.cn
 adextensioncontrol.tudou.com
 iwstat.tudou.com
 nstat.tudou.com
 stats.tudou.com
 adplay.tudou.com
 adcontrol.tudou.com
 stat.tudou.com
 1.allyes.com.cn
 analytics.ku6.com
 gug.ku6cdn.com
 ku6.allyes.com
 ku6afp.allyes.com
 pq.stat.ku6.com
 st.vq.ku6.cn
 stat0.888.ku6.com
 stat1.888.ku6.com
 stat2.888.ku6.com
 stat3.888.ku6.com
 static.ku6.com
 v0.stat.ku6.com
 v1.stat.ku6.com
 v2.stat.ku6.com
 v3.stat.ku6.com
 86file.megajoy.com
 86get.joy.cn
 86log.joy.cn
 casting.openv.com
 uniclick.openv.com
 server1.adpolestar.net
 advstat.xunlei.com
 mpv.sandai.net
 adapi.starschina.com
 countatm.cp12.wasu.tv
 adsys.chinacloudapp.cn
 advapi.ahtv.cn
 anquan.luomi.com
 ad.wx.com
 stats.umsns.com
 track.dmp.youmi.net
 s.qtad.qingting.fm
 r.inad.com
 adserviceretry.kglink.cn
 cdn.yimg.com
 mp.nextmedia.com
 m.zhuanzhuzibu.com
 syy.dxwpedu.me
 vpn.ch-hr12333.com
 img.wusnz.cn
 x.ojgoy.cn
 i.luyongkang.top
 m.szwjzl.cn
 po.jiangchangbo.com
 ee.x8r9m.cn
 v.37uta.cn
 rz.w8r4q.cn
 ok.4qn9c.cn
 www.qchannel02.cn
 m.xsm98e.cn
 e.xsm98e.cn
 i8.i8ggwm.com
 e.crashlytics.com
 pagead.googlesyndication.com
 pagead1.googlesyndication.com
 ad.googleanalysis.mobi
 stat.googleanalysis.mobi
 static.googeadsserving.cn
 ads.admoda.com
 ad.madvertise.de
 admicro2.vcmedia.vn
 img.ads.mojiva.com
 img.ads.mocean.mobi
 banners.bigmobileads.com
 images.millennialmedia.com
 i.tapit.com
 medrx.sensis.com.au
 ads.n-ws.org
 ads.smartdevicemedia.com
 cdn.vdopia.com
 api.yp.com
 android-sdk31.transpera.com
 ads.matomymobile.com
 ads.adiquity.com
 cdn.us.goldspotmedia.com
 ads.ookla.com
 mobiledl.adobe.com
 d3anogn3pbtk4v.cloudfront.net
 d2bgg7rjywcwsy.cloudfront.net
 atti.velti.com
 ru.velti.com
 mwc.velti.com
 bo.jumptap.com
 i.jumptap.com
 uk-ad2.adinfuse.com
 go.adinfuse.com
 ad1.adinfuse.com
 ad2.adinfuse.com
 sky.adinfuse.com
 orange-fr.adinfuse.com
 sky-connect.adinfuse.com
 uk-go.adinfuse.com
 orangeuk-mc.adinfuse.com
 intouch.adinfuse.com
 funnel0.adinfuse.com
 swappit.tapad.com
 adsrv1.tapad.com
 ads1.mojiva.com
 ads2.mojiva.com
 ads3.mojiva.com
 ads4.mojiva.com
 ads5.mojiva.com
 adtracker.inmobi.com
 img.ads1.mojiva.com
 img.ads2.mojiva.com
 img.ads3.mojiva.com
 img.ads4.mojiva.com
 img.ads1.mocean.mobi
 img.ads2.mocean.mobi
 img.ads3.mocean.mobi
 img.ads4.mocean.mobi
 tcy.smartadserver.com
 data.mobclix.com
 s.mobclix.com
 ads.mdotm.com
 cdn.mdotm.com
 a.admob.com
 analytics.admob.com
 p.admob.com
 ad.leadboltmobile.net
 t.medialytics.com
 adfarm.mediaplex.com
 cpro.baidu.cn
 btlaunch.baidu.com
 adsclick.qq.com
 adsqqclick.qq.com
 tajs.qq.com
 tcss.qq.com
 a.irs01.com
 bitauto.irs01.com
 h.irs01.com
 m.irs01.com
 pcauto.irs01.com
 qq.irs01.com
 v.irs01.com
 v12-r0566gbscjw.z.irs01.com
 yyt.irs01.com
 alog.umeng.co
 uop.umeng.com
 oc.umeng.co
 cpull.360.cn
 api.appjiagu.com
 folder.advmob.cn
 feedback.whalecloud.com
 ad.evozi.com
 api.adcome.cn
 music.adcome.cn
 res.adcome.cn
 cm.admaster.com.cn
 iclick.cm.admaster.com.cn
 letv.cm.admaster.com.cn
 pptv.cm.admaster.com.cn
 pxl.idx.admaster.com.cn
 sohutv.cm.admaster.com.cn
 vamaker.cm.admaster.com.cn
 wisemedia.cm.admaster.com.cn
 mediapro.pro.cn
 dmp.adpush.cn
 img.adpush.cn
 net.adpush.cn
 ssp.adpush.cn
 zc.adpush.cn
 www.adpush.cn
 config.adsage.cn
 config.adsage.com
 entry.adsage.com
 mobi.adsage.com
 zt.adsage.com
 0127.adsame.com
 114study.adsame.com
 adplace.adsame.com
 dolphin.adsame.com
 dolphin1.adsame.com
 eagle.adsame.com
 eagledemo.adsame.com
 eaglepro.adsame.com
 meihua.adsame.com
 sammax.adsame.com
 techweb.adsame.com
 vdcci.adsame.com
 vtechweb.adsame.com
 xcar.adsame.com
 c.domob.cn
 dvx-android.domob.cn
 e.domob.com.cn
 r.domob.cn
 r.ow.domob.cn
 scc.domob.cn
 sdl.domob.cn
 swx.domob.cn
 c.duomeng.cn
 c.duomeng.net
 c1.guomob.com
 code.guomob.com
 pic.guomob.com
 t3.guomob.com
 t4.guomob.com
 www.guomob.com
 a.ads.cn.miaozhen.com
 a.cn.miaozhen.com
 a.tac.miaozhen.com
 c.m.cn.miaozhen.com
 c.x.cn.miaozhen.com
 e.ads.cn.miaozhen.com
 e.mbm.cn.miaozhen.com
 e.x.cn.miaozhen.com
 exchange.ipdx.cn.miaozhen.com
 g.mbm.cn.miaozhen.com
 g.x.cn.miaozhen.com
 gs.m.cn.miaozhen.com
 mse.mbm.cn.miaozhen.com
 msg.mbm.cn.miaozhen.com
 qq.m.cn.miaozhen.com
 t.pg.cn.miaozhen.com
 wisem-cm.cn.miaozhen.com
 yktd.ads.cn.miaozhen.com
 yktd.cm.cn.miaozhen.com
 api.cmt.mob.com
 ssl.ymapp.com
 video.ymapp.com
 apk.static.youmi.net
 banner.img.static.youmi.net
 pkg-cdn.youmi.net
 zc.adpush.cn
 ad1.sina.com.cn
 ad5.sina.com.cn
 a.domob.cn
 z.domob.cn
 ad.xxguan.cn
 zt.adsage.com
 ads-west-colo.adsymptotic.com
 adsina.allyes.com
 cs6.cnzz.com
 adv2.downsave.com
 ad.dqwjzm.com
 e-ltvp.inmobi.com
 rules-ltvp.inmobi.com
 a.ai.inmobi.com
 ad.jsnbrynb.com
 ads.bssdl.kugou.com
 adfarm.mediaplex.com
 adimg.qxlsjw.com
 ad4.sina.com
 adstream.123.sogoucdn.com
 adnet.sohu.com
 track.dmp.youmi.net
 ad.cdn.sex

The script also generates a hosts file consisted of active entries.

[active.txt](https://github.com/jdlingyu/ad-wars/files/6635569/active.txt)

**Comment by jdlingyu** [comment]
> PyFunceble -f https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts -c --dns 1.2.4.8 8.8.8.8
> 
> The project decides whether a domain is active by three dimensions, HTTP status code, WHOIS record and DNS Lookup.
> 
> More info: https://pyfunceble.readthedocs.io/en/latest/usage/index.html#from-a-terminal
> 
> These domains are marked as INACTIVE
> 
> m.irs01.com z.irs01.com sdk2.youguoquan.com rlog-video.conn.aiseet.atianqi.com afp.qiyi.com focusbaiduafp.allyes.com sohu.irs01.com api.game.letvstore.com dev.dc.letv.com msg.m.letv.com api.adv.ott.cibntv.net tpptv.ipdx.cn.miaozhen.com mdrecv.app.cntvwb.cn sdapprecv.app.cntvwb.cn vdapprecv.app.cntvwb.cn a.cctv.com dspserver.ad.cmvideo.cn test.ad.cmvideo.cn adextensioncontrol.tudou.com iwstat.tudou.com nstat.tudou.com stats.tudou.com adplay.tudou.com adcontrol.tudou.com stat.tudou.com 1.allyes.com.cn analytics.ku6.com gug.ku6cdn.com ku6.allyes.com ku6afp.allyes.com pq.stat.ku6.com st.vq.ku6.cn stat0.888.ku6.com stat1.888.ku6.com stat2.888.ku6.com stat3.888.ku6.com static.ku6.com v0.stat.ku6.com v1.stat.ku6.com v2.stat.ku6.com v3.stat.ku6.com 86file.megajoy.com 86get.joy.cn 86log.joy.cn casting.openv.com uniclick.openv.com server1.adpolestar.net advstat.xunlei.com mpv.sandai.net adapi.starschina.com countatm.cp12.wasu.tv adsys.chinacloudapp.cn advapi.ahtv.cn anquan.luomi.com ad.wx.com stats.umsns.com track.dmp.youmi.net s.qtad.qingting.fm r.inad.com adserviceretry.kglink.cn cdn.yimg.com mp.nextmedia.com m.zhuanzhuzibu.com syy.dxwpedu.me vpn.ch-hr12333.com img.wusnz.cn x.ojgoy.cn i.luyongkang.top m.szwjzl.cn po.jiangchangbo.com ee.x8r9m.cn v.37uta.cn rz.w8r4q.cn ok.4qn9c.cn [www.qchannel02.cn](http://www.qchannel02.cn) m.xsm98e.cn e.xsm98e.cn i8.i8ggwm.com e.crashlytics.com pagead.googlesyndication.com pagead1.googlesyndication.com ad.googleanalysis.mobi stat.googleanalysis.mobi static.googeadsserving.cn ads.admoda.com ad.madvertise.de admicro2.vcmedia.vn img.ads.mojiva.com img.ads.mocean.mobi banners.bigmobileads.com images.millennialmedia.com i.tapit.com medrx.sensis.com.au ads.n-ws.org ads.smartdevicemedia.com cdn.vdopia.com api.yp.com android-sdk31.transpera.com ads.matomymobile.com ads.adiquity.com cdn.us.goldspotmedia.com ads.ookla.com mobiledl.adobe.com d3anogn3pbtk4v.cloudfront.net d2bgg7rjywcwsy.cloudfront.net atti.velti.com ru.velti.com mwc.velti.com bo.jumptap.com i.jumptap.com uk-ad2.adinfuse.com go.adinfuse.com ad1.adinfuse.com ad2.adinfuse.com sky.adinfuse.com orange-fr.adinfuse.com sky-connect.adinfuse.com uk-go.adinfuse.com orangeuk-mc.adinfuse.com intouch.adinfuse.com funnel0.adinfuse.com swappit.tapad.com adsrv1.tapad.com ads1.mojiva.com ads2.mojiva.com ads3.mojiva.com ads4.mojiva.com ads5.mojiva.com adtracker.inmobi.com img.ads1.mojiva.com img.ads2.mojiva.com img.ads3.mojiva.com img.ads4.mojiva.com img.ads1.mocean.mobi img.ads2.mocean.mobi img.ads3.mocean.mobi img.ads4.mocean.mobi tcy.smartadserver.com data.mobclix.com s.mobclix.com ads.mdotm.com cdn.mdotm.com a.admob.com analytics.admob.com p.admob.com ad.leadboltmobile.net t.medialytics.com adfarm.mediaplex.com cpro.baidu.cn btlaunch.baidu.com adsclick.qq.com adsqqclick.qq.com tajs.qq.com tcss.qq.com a.irs01.com bitauto.irs01.com h.irs01.com m.irs01.com pcauto.irs01.com qq.irs01.com v.irs01.com v12-r0566gbscjw.z.irs01.com yyt.irs01.com alog.umeng.co uop.umeng.com oc.umeng.co cpull.360.cn api.appjiagu.com folder.advmob.cn feedback.whalecloud.com ad.evozi.com api.adcome.cn music.adcome.cn res.adcome.cn cm.admaster.com.cn iclick.cm.admaster.com.cn letv.cm.admaster.com.cn pptv.cm.admaster.com.cn pxl.idx.admaster.com.cn sohutv.cm.admaster.com.cn vamaker.cm.admaster.com.cn wisemedia.cm.admaster.com.cn mediapro.pro.cn dmp.adpush.cn img.adpush.cn net.adpush.cn ssp.adpush.cn zc.adpush.cn [www.adpush.cn](http://www.adpush.cn) config.adsage.cn config.adsage.com entry.adsage.com mobi.adsage.com zt.adsage.com 0127.adsame.com 114study.adsame.com adplace.adsame.com dolphin.adsame.com dolphin1.adsame.com eagle.adsame.com eagledemo.adsame.com eaglepro.adsame.com meihua.adsame.com sammax.adsame.com techweb.adsame.com vdcci.adsame.com vtechweb.adsame.com xcar.adsame.com c.domob.cn dvx-android.domob.cn e.domob.com.cn r.domob.cn r.ow.domob.cn scc.domob.cn sdl.domob.cn swx.domob.cn c.duomeng.cn c.duomeng.net c1.guomob.com code.guomob.com pic.guomob.com t3.guomob.com t4.guomob.com [www.guomob.com](http://www.guomob.com) a.ads.cn.miaozhen.com a.cn.miaozhen.com a.tac.miaozhen.com c.m.cn.miaozhen.com c.x.cn.miaozhen.com e.ads.cn.miaozhen.com e.mbm.cn.miaozhen.com e.x.cn.miaozhen.com exchange.ipdx.cn.miaozhen.com g.mbm.cn.miaozhen.com g.x.cn.miaozhen.com gs.m.cn.miaozhen.com mse.mbm.cn.miaozhen.com msg.mbm.cn.miaozhen.com qq.m.cn.miaozhen.com t.pg.cn.miaozhen.com wisem-cm.cn.miaozhen.com yktd.ads.cn.miaozhen.com yktd.cm.cn.miaozhen.com api.cmt.mob.com ssl.ymapp.com video.ymapp.com apk.static.youmi.net banner.img.static.youmi.net pkg-cdn.youmi.net zc.adpush.cn ad1.sina.com.cn ad5.sina.com.cn a.domob.cn z.domob.cn ad.xxguan.cn zt.adsage.com ads-west-colo.adsymptotic.com adsina.allyes.com cs6.cnzz.com adv2.downsave.com ad.dqwjzm.com e-ltvp.inmobi.com rules-ltvp.inmobi.com a.ai.inmobi.com ad.jsnbrynb.com ads.bssdl.kugou.com adfarm.mediaplex.com adimg.qxlsjw.com ad4.sina.com adstream.123.sogoucdn.com adnet.sohu.com track.dmp.youmi.net ad.cdn.sex
> 
> The script also generates a hosts file consisted of active entries.
> 
> [active.txt](https://github.com/jdlingyu/ad-wars/files/6635569/active.txt)

nice 💯
