### ISSUE TITLE
大圣净化在太极·阴上无效

### ISSUE THREAD

**Issue by jiahe224** [jdlingyu/ad-wars#2]
用云端url规则去不掉公众号广告，规则作者用的不是太极·阴可起效

**Comment by jiahe224** [comment]
没回应吗

**Comment by jdlingyu** [comment]
> 用云端url规则去不掉公众号广告，规则作者用的不是太极·阴可起效

经过测试目前大部分已经不生效了，广告已经不走API了，太极.阴 一直不生效。
